### ISSUE TITLE
Unexpected output stream from ConvertFrom-RSAPrivateKeyPEM

### ISSUE THREAD

**Issue by marklindell** [bamcisnetworks/BAMCIS.Crypto#1]
The following is occurring when attempting to use ConvertFrom-RSAPrivateKeyPEM to get a PEM.

```
InvalidArgument: D:\Documents\PowerShell\Modules\BAMCIS.Crypto\1.0.0.0\BAMCIS.Crypto.psm1:997:21
Line |
 997 |  …             [System.Security.Cryptography.RSACryptoServiceProvider]$R …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Security.Cryptography.RSACryptoServiceProvider".
```

On line #101 $KeyParts is being sent to the output stream along with $RSA on line #113. It does not seem that this was intended for this function as it's purpose is to create

**Comment by hakenmt** [comment]
That looks like a bug/typo, I don't think the `$KeyParts` variable was intended to go to the output stream.

**Comment by marklindell** [comment]
Are you going to publish version 1.0.1 to powershell gallery?

[https://www.powershellgallery.com/packages/BAMCIS.Crypto](https://www.powershellgallery.com/packages/BAMCIS.Crypto)

**Comment by hakenmt** [comment]
Yes, will provide the update this morning.
